//! Everything that touches the plugin's private data folder.
//! Needs the `fs.read.data` and `fs.write.data` permissions (see `metadata()`).

use crate::lang::{Table, normalize};
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};
use tracing::warn;

/// Languages shipped inside the plugin. They are (a) registered in memory as
/// the lowest-priority source, so new keys in a plugin update always work, and
/// (b) copied to `translations/`, as editable files for admins (see `seed_defaults`).
pub const BUNDLED: &[(&str, &str)] = &[
    // BEGIN GENERATED by tools/translations.py (`python3 tools/translations.py sync`): don't edit by hand
    ("af_za", include_str!("../defaults/af_za.json")),
    ("ar_sa", include_str!("../defaults/ar_sa.json")),
    ("ast_es", include_str!("../defaults/ast_es.json")),
    ("az_az", include_str!("../defaults/az_az.json")),
    ("ba_ru", include_str!("../defaults/ba_ru.json")),
    ("bar", include_str!("../defaults/bar.json")),
    ("be_by", include_str!("../defaults/be_by.json")),
    ("bg_bg", include_str!("../defaults/bg_bg.json")),
    ("br_fr", include_str!("../defaults/br_fr.json")),
    ("brb", include_str!("../defaults/brb.json")),
    ("bs_ba", include_str!("../defaults/bs_ba.json")),
    ("ca_es", include_str!("../defaults/ca_es.json")),
    ("cs_cz", include_str!("../defaults/cs_cz.json")),
    ("cy_gb", include_str!("../defaults/cy_gb.json")),
    ("da_dk", include_str!("../defaults/da_dk.json")),
    ("de_de", include_str!("../defaults/de_de.json")),
    ("el_gr", include_str!("../defaults/el_gr.json")),
    ("en_pt", include_str!("../defaults/en_pt.json")),
    ("en_ud", include_str!("../defaults/en_ud.json")),
    ("en_us", include_str!("../defaults/en_us.json")),
    ("enp", include_str!("../defaults/enp.json")),
    ("enws", include_str!("../defaults/enws.json")),
    ("eo_uy", include_str!("../defaults/eo_uy.json")),
    ("es_es", include_str!("../defaults/es_es.json")),
    ("esan", include_str!("../defaults/esan.json")),
    ("et_ee", include_str!("../defaults/et_ee.json")),
    ("eu_es", include_str!("../defaults/eu_es.json")),
    ("fa_ir", include_str!("../defaults/fa_ir.json")),
    ("fi_fi", include_str!("../defaults/fi_fi.json")),
    ("fil_ph", include_str!("../defaults/fil_ph.json")),
    ("fo_fo", include_str!("../defaults/fo_fo.json")),
    ("fr_fr", include_str!("../defaults/fr_fr.json")),
    ("fra_de", include_str!("../defaults/fra_de.json")),
    ("fur_it", include_str!("../defaults/fur_it.json")),
    ("fy_nl", include_str!("../defaults/fy_nl.json")),
    ("ga_ie", include_str!("../defaults/ga_ie.json")),
    ("gd_gb", include_str!("../defaults/gd_gb.json")),
    ("gl_es", include_str!("../defaults/gl_es.json")),
    ("haw_us", include_str!("../defaults/haw_us.json")),
    ("he_il", include_str!("../defaults/he_il.json")),
    ("hi_in", include_str!("../defaults/hi_in.json")),
    ("hr_hr", include_str!("../defaults/hr_hr.json")),
    ("hu_hu", include_str!("../defaults/hu_hu.json")),
    ("hy_am", include_str!("../defaults/hy_am.json")),
    ("id_id", include_str!("../defaults/id_id.json")),
    ("ig_ng", include_str!("../defaults/ig_ng.json")),
    ("io_en", include_str!("../defaults/io_en.json")),
    ("is_is", include_str!("../defaults/is_is.json")),
    ("isv", include_str!("../defaults/isv.json")),
    ("it_it", include_str!("../defaults/it_it.json")),
    ("ja_jp", include_str!("../defaults/ja_jp.json")),
    ("jbo_en", include_str!("../defaults/jbo_en.json")),
    ("ka_ge", include_str!("../defaults/ka_ge.json")),
    ("kk_kz", include_str!("../defaults/kk_kz.json")),
    ("kn_in", include_str!("../defaults/kn_in.json")),
    ("ko_kr", include_str!("../defaults/ko_kr.json")),
    ("ksh", include_str!("../defaults/ksh.json")),
    ("kw_gb", include_str!("../defaults/kw_gb.json")),
    ("la_la", include_str!("../defaults/la_la.json")),
    ("lb_lu", include_str!("../defaults/lb_lu.json")),
    ("li_li", include_str!("../defaults/li_li.json")),
    ("lmo", include_str!("../defaults/lmo.json")),
    ("lo_la", include_str!("../defaults/lo_la.json")),
    ("lol_us", include_str!("../defaults/lol_us.json")),
    ("lt_lt", include_str!("../defaults/lt_lt.json")),
    ("lv_lv", include_str!("../defaults/lv_lv.json")),
    ("lzh", include_str!("../defaults/lzh.json")),
    ("mk_mk", include_str!("../defaults/mk_mk.json")),
    ("mn_mn", include_str!("../defaults/mn_mn.json")),
    ("ms_my", include_str!("../defaults/ms_my.json")),
    ("mt_mt", include_str!("../defaults/mt_mt.json")),
    ("nah", include_str!("../defaults/nah.json")),
    ("nds_de", include_str!("../defaults/nds_de.json")),
    ("nl_nl", include_str!("../defaults/nl_nl.json")),
    ("nn_no", include_str!("../defaults/nn_no.json")),
    ("no_no", include_str!("../defaults/no_no.json")),
    ("oc_fr", include_str!("../defaults/oc_fr.json")),
    ("ovd", include_str!("../defaults/ovd.json")),
    ("pl_pl", include_str!("../defaults/pl_pl.json")),
    ("pls", include_str!("../defaults/pls.json")),
    ("pt_br", include_str!("../defaults/pt_br.json")),
    ("pt_pt", include_str!("../defaults/pt_pt.json")),
    ("qya_aa", include_str!("../defaults/qya_aa.json")),
    ("ro_ro", include_str!("../defaults/ro_ro.json")),
    ("ru_ru", include_str!("../defaults/ru_ru.json")),
    ("ry_ua", include_str!("../defaults/ry_ua.json")),
    ("sah_sah", include_str!("../defaults/sah_sah.json")),
    ("se_no", include_str!("../defaults/se_no.json")),
    ("sk_sk", include_str!("../defaults/sk_sk.json")),
    ("sl_si", include_str!("../defaults/sl_si.json")),
    ("so_so", include_str!("../defaults/so_so.json")),
    ("sq_al", include_str!("../defaults/sq_al.json")),
    ("sr_sp", include_str!("../defaults/sr_sp.json")),
    ("sv_se", include_str!("../defaults/sv_se.json")),
    ("sxu", include_str!("../defaults/sxu.json")),
    ("szl", include_str!("../defaults/szl.json")),
    ("ta_in", include_str!("../defaults/ta_in.json")),
    ("th_th", include_str!("../defaults/th_th.json")),
    ("tl_ph", include_str!("../defaults/tl_ph.json")),
    ("tlh_aa", include_str!("../defaults/tlh_aa.json")),
    ("tok", include_str!("../defaults/tok.json")),
    ("tr_tr", include_str!("../defaults/tr_tr.json")),
    ("tt_ru", include_str!("../defaults/tt_ru.json")),
    ("tzl_tzl", include_str!("../defaults/tzl_tzl.json")),
    ("uk_ua", include_str!("../defaults/uk_ua.json")),
    ("val_es", include_str!("../defaults/val_es.json")),
    ("vec_it", include_str!("../defaults/vec_it.json")),
    ("vi_vn", include_str!("../defaults/vi_vn.json")),
    ("vp_vl", include_str!("../defaults/vp_vl.json")),
    ("yi_de", include_str!("../defaults/yi_de.json")),
    ("yo_ng", include_str!("../defaults/yo_ng.json")),
    ("zh_cn", include_str!("../defaults/zh_cn.json")),
    ("zh_hk", include_str!("../defaults/zh_hk.json")),
    ("zh_tw", include_str!("../defaults/zh_tw.json")),
    ("zlm_arab", include_str!("../defaults/zlm_arab.json")),
    // END GENERATED
];

/// Where the editable language files live: `<data folder>/translations/`.
/// (Versions before 0.2 used `lang/`; `seed_defaults` renames it on first start.)
fn lang_dir(base: &Path) -> PathBuf {
    base.join("translations")
}

fn prefs_path(base: &Path) -> PathBuf {
    base.join("players.json")
}

/// Parse a flat `{ "key": "text" }` JSON object.
pub fn parse_entries(json: &str) -> Result<HashMap<String, String>, serde_json::Error> {
    serde_json::from_str(json)
}

/// FNV-1a, 64 bit. Used to tell "file is exactly what we wrote" from "an admin edited it".
/// (Not `DefaultHasher`: its output isn't guaranteed stable across Rust versions.)
fn fnv_hex(text: &str) -> String {
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    for byte in text.as_bytes() {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(0x0000_0100_0000_01b3);
    }
    format!("{hash:016x}")
}

/// Remembers the hash of every file we wrote, so a plugin update can refresh files that are
/// still untouched while never clobbering an admin's edits. Lives next to `players.json`,
/// not inside `translations/` (everything in there is loaded as a language).
fn seeded_path(base: &Path) -> PathBuf {
    base.join("seeded.json")
}

/// Put the bundled translations into `translations/` so admins can read and edit them.
///
/// - Missing file: written.
/// - File still exactly as we last wrote it, and this plugin version ships a newer
///   one: updated, so translation fixes reach servers that never touched the file.
/// - Anything else (an admin edited it, or we never wrote it): left alone.
pub fn seed_defaults(base: &Path) {
    let dir = lang_dir(base);

    // Migrate the pre-0.2 `lang/` folder, keeping any edits an admin made.
    let legacy = base.join("lang");
    if legacy.is_dir() && !dir.exists() {
        if let Err(e) = fs::rename(&legacy, &dir) {
            warn!("could not rename lang/ to translations/: {e}");
        }
    }

    if let Err(e) = fs::create_dir_all(&dir) {
        warn!("could not create {}: {e}", dir.display());
        return;
    }

    let mut recorded: HashMap<String, String> = fs::read_to_string(seeded_path(base))
        .ok()
        .and_then(|s| serde_json::from_str(&s).ok())
        .unwrap_or_default();
    let mut changed = false;

    for (code, contents) in BUNDLED {
        let path = dir.join(format!("{code}.json"));
        let shipped = fnv_hex(contents);

        let should_write = if !path.exists() {
            true
        } else if let Ok(on_disk) = fs::read_to_string(&path) {
            let current = fnv_hex(&on_disk);
            current != shipped && recorded.get(*code) == Some(&current)
        } else {
            false
        };

        if should_write {
            match fs::write(&path, contents) {
                Ok(()) => {
                    recorded.insert((*code).to_string(), shipped);
                    changed = true;
                }
                Err(e) => warn!("could not write {}: {e}", path.display()),
            }
        }
    }

    if changed {
        match serde_json::to_string_pretty(&recorded) {
            Ok(json) => {
                if let Err(e) = fs::write(seeded_path(base), json) {
                    warn!("could not save seeded.json: {e}");
                }
            }
            Err(e) => warn!("could not encode seeded.json: {e}"),
        }
    }
}

/// Read every `lang/*.json`. The file name (without `.json`) is the language code.
/// A broken file is skipped with a warning instead of failing the whole load.
pub fn load_files(base: &Path) -> Table {
    let mut table = Table::new();
    let entries = match fs::read_dir(lang_dir(base)) {
        Ok(e) => e,
        Err(e) => {
            warn!("could not read language folder: {e}");
            return table;
        }
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("json") {
            continue;
        }
        let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else {
            continue;
        };
        match fs::read_to_string(&path)
            .map_err(|e| e.to_string())
            .and_then(|s| parse_entries(&s).map_err(|e| e.to_string()))
        {
            Ok(map) => {
                table.insert(normalize(stem), map);
            }
            Err(e) => warn!("skipping {}: {e}", path.display()),
        }
    }
    table
}

/// Optional `aliases.json`: `{ "english": "en_us", "tupi": "pt_br" }`.
pub fn load_aliases(base: &Path) -> HashMap<String, String> {
    match fs::read_to_string(base.join("aliases.json")) {
        Ok(s) => serde_json::from_str(&s).unwrap_or_else(|e| {
            warn!("aliases.json is invalid, ignoring it: {e}");
            HashMap::new()
        }),
        Err(_) => HashMap::new(),
    }
}

pub fn load_prefs(base: &Path) -> HashMap<String, String> {
    match fs::read_to_string(prefs_path(base)) {
        Ok(s) => serde_json::from_str(&s).unwrap_or_else(|e| {
            warn!("players.json is invalid, ignoring it: {e}");
            HashMap::new()
        }),
        Err(_) => HashMap::new(), // first run
    }
}

pub fn save_prefs(base: &Path, prefs: &HashMap<String, String>) -> Result<(), String> {
    let json = serde_json::to_string_pretty(prefs).map_err(|e| e.to_string())?;
    fs::write(prefs_path(base), json).map_err(|e| e.to_string())
}
