#!/usr/bin/env python3
"""Translation tooling for SimpleLang. Python 3, standard library only.

  status [--write]            what's translated, what's missing (--write: update TRANSLATIONS.md)
  prompt CODE... | --missing  build ready-to-paste prompts for an LLM (--out DIR: one file per language)
  import PATH...              validate model answers and add them as translations
  sync [--check]              keep the Rust list of bundled languages in sync with the files

Typical flow with a local model, see TRANSLATING.md:
  python3 tools/translations.py prompt --missing --out tools/work/prompts
  ... run your model on each prompt, save its reply as tools/work/answers/<code>.json ...
  python3 tools/translations.py import tools/work/answers
"""
import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULTS = ROOT / "simplelang" / "defaults"
STORAGE = ROOT / "simplelang" / "src" / "storage.rs"
CATALOGUE = DEFAULTS / "minecraft_languages.json"
STATUS_DOC = ROOT / "TRANSLATIONS.md"
SOURCE = "en_us"  # the reference language everything is translated from

PLACEHOLDER = re.compile(r"\{(\d+)\}")
BEGIN = "    // BEGIN GENERATED by tools/translations.py (`python3 tools/translations.py sync`): don't edit by hand\n"
END = "    // END GENERATED\n"


# ---------------------------------------------------------------- data access

def read_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, data) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def catalogue() -> dict:
    """code -> {code, name, native?}, in the catalogue's order."""
    return {e["code"]: e for e in read_json(CATALOGUE)}


def english() -> dict:
    return read_json(DEFAULTS / f"{SOURCE}.json")


def translated_codes() -> list:
    return sorted(p.stem for p in DEFAULTS.glob("*.json") if p != CATALOGUE)


def needed(cat: dict, done: set) -> list:
    """Languages that still want a translation. Regional variants marked `variant_of`
    (es_mx, de_at, en_gb, ...) don't: SimpleLang already serves them from their family."""
    return [c for c, e in cat.items() if c not in done and not e.get("variant_of")]


def display_name(entry: dict) -> str:
    """What goes into `simplelang.lang.name`: the language's own name if known."""
    return entry.get("native") or entry["name"]


# ----------------------------------------------------------------- validation

def validate(data, en: dict) -> list:
    """Problems with one language's strings. Empty list = fine.
    `simplelang.lang.name` is optional in an answer: we fill it from the catalogue."""
    if not isinstance(data, dict):
        return ["answer is not a JSON object"]
    errors = []
    name_key = "simplelang.lang.name"
    wanted = [k for k in en if k != name_key]
    missing = [k for k in wanted if k not in data]
    extra = [k for k in data if k not in en]
    if missing:
        errors.append("missing keys: " + ", ".join(missing))
    if extra:
        errors.append("unknown keys: " + ", ".join(extra))
    for key in wanted:
        value = data.get(key)
        if value is None:
            continue
        if not isinstance(value, str) or not value.strip():
            errors.append(f"{key}: must be a non-empty string")
            continue
        if any(ord(c) < 32 for c in value):
            errors.append(f"{key}: contains a line break or control character")
        want = sorted(PLACEHOLDER.findall(en[key]))
        got = sorted(PLACEHOLDER.findall(value))
        if want != got:
            errors.append(f"{key}: placeholders {got}, English has {want}")
    return errors


def extract_json(text: str):
    """Pull the JSON object out of a model reply (tolerates code fences and chatter)."""
    start, end = text.find("{"), text.rfind("}")
    if start == -1 or end <= start:
        return None
    try:
        return json.loads(text[start : end + 1])
    except json.JSONDecodeError:
        return None


# ------------------------------------------------------------------- commands

def cmd_status(args) -> int:
    cat, done = catalogue(), set(translated_codes())
    todo = needed(cat, done)
    variants = [c for c, e in cat.items() if e.get("variant_of") and c not in done]
    print(
        f"{len(cat)} Minecraft languages: {len(done)} translated (incl. English source), "
        f"{len(variants)} served by a sibling language, {len(todo)} still need a translation"
    )
    orphans = sorted(done - set(cat))
    if orphans:
        print("files not in the catalogue:", ", ".join(orphans))
    print("needed:", ", ".join(todo) if todo else "none")
    if args.write:
        rows = []
        for code, e in cat.items():
            if code == SOURCE:
                state = "✅ source"
            elif code in done:
                state = "✅"
            elif e.get("variant_of"):
                state = f"↪ uses `{e['variant_of']}`"
            else:
                state = "⬜ needed"
            rows.append(f"| `{code}` | {e['name']} | {e.get('native', '')} | {state} |")
        STATUS_DOC.write_text(
            "# Translation status\n\n"
            "Every Minecraft language can be selected with `/lang`; this table shows which ones\n"
            "also have SimpleLang's own messages translated. The others fall back to English.\n"
            "Regional variants marked ↪ are served by their main language and don't need their own file.\n\n"
            "**All translations so far are machine-generated and haven't been reviewed by native\n"
            "speakers.** Corrections are very welcome. See [TRANSLATING.md](TRANSLATING.md).\n\n"
            f"**{len(done)} of {len(cat)}** languages have their own translation; "
            f"{len(todo)} still needed.\n\n"
            "| Code | Language | Native name | Status |\n|---|---|---|---|\n"
            + "\n".join(rows)
            + "\n\n<sub>Generated by `python3 tools/translations.py status --write`.</sub>\n",
            encoding="utf-8",
        )
        print(f"wrote {STATUS_DOC.name}")
    return 0


PROMPT = """You are translating the player-facing messages of a Minecraft server plugin called SimpleLang into {english} ({native}). Language code: {code}.

Below is the English source as JSON. Translate every VALUE into {english}. Keep every KEY unchanged.

Rules:
1. Keep every placeholder such as {{0}} exactly as written. Do not translate, remove, add or renumber them. A placeholder may move if the grammar needs it.
2. Do NOT translate these: SimpleLang, Minecraft, the commands /lang, /lang auto and /lang list, and the example codes english, portugues and pt_br.
3. In the "usage" message, translate the word inside the angle brackets (<language>) but keep the angle brackets.
4. Natural, friendly, concise wording, as in a game's own interface. Use the polite or informal register that is normal for games in {english}. Plain text only: no markdown, no emoji, no line breaks inside a value.
5. Use the quotation marks that are normal in {english} around the "{{0}}" in the unknown-language message.
6. "simplelang.lang.name" is the language's own name: use "{name}".

Reply with ONLY one JSON object with the same keys: no explanation, no markdown fences. If you cannot translate {english} reliably, reply with exactly {{"skip": true}} instead of guessing.

English source:
{source}
"""


def build_prompt(code: str, entry: dict, en: dict) -> str:
    return PROMPT.format(
        english=entry["name"],
        native=entry.get("native") or entry["name"],
        code=code,
        name=display_name(entry),
        source=json.dumps(en, ensure_ascii=False, indent=2),
    )


def cmd_prompt(args) -> int:
    cat, en = catalogue(), english()
    codes = list(args.codes)
    if args.missing:
        codes += [c for c in needed(cat, set(translated_codes())) if c not in codes]
    if not codes:
        print("nothing to do: give language codes or use --missing")
        return 1
    unknown = [c for c in codes if c not in cat]
    if unknown:
        print("not in the catalogue:", ", ".join(unknown))
        return 1
    if args.out:
        out = Path(args.out)
        out.mkdir(parents=True, exist_ok=True)
        for code in codes:
            (out / f"{code}.txt").write_text(build_prompt(code, cat[code], en), encoding="utf-8")
        print(f"wrote {len(codes)} prompt(s) to {out}/  (save each reply as <code>.json, then run `import`)")
    else:
        for code in codes:
            print(f"===== {code} =====")
            print(build_prompt(code, cat[code], en))
    return 0


def cmd_import(args) -> int:
    cat, en = catalogue(), english()
    files = []
    for raw in args.paths:
        p = Path(raw)
        files += sorted(p.glob("*.json")) if p.is_dir() else [p]
    if not files:
        print("no files to import")
        return 1
    added, problems = [], 0
    for f in files:
        code = args.code or f.stem
        if code == SOURCE:
            print(f"  skip  {f.name}: {SOURCE} is the English source")
            continue
        if code not in cat:
            print(f"  FAIL  {f.name}: '{code}' is not in minecraft_languages.json (file name must be the language code)")
            problems += 1
            continue
        data = extract_json(f.read_text(encoding="utf-8"))
        if data is None:
            print(f"  FAIL  {code}: no JSON object found in {f.name}")
            problems += 1
            continue
        if isinstance(data, dict) and data.get("skip") is True:
            print(f"  skip  {code}: the model declined (not confident)")
            continue
        errors = validate(data, en)
        if errors:
            print(f"  FAIL  {code}:")
            for e in errors:
                print(f"          - {e}")
            problems += 1
            continue
        target = DEFAULTS / f"{code}.json"
        if target.exists() and not args.overwrite:
            print(f"  skip  {code}: already translated (use --overwrite to replace)")
            continue
        out = {"simplelang.lang.name": display_name(cat[code])}
        out.update({k: data[k] for k in en if k != "simplelang.lang.name"})
        write_json(target, out)
        added.append(code)
        print(f"  ok    {code}")
    if added:
        sync(check=False)
    print(f"\nadded {len(added)}, rejected {problems}")
    return 1 if problems else 0


def sync(check: bool) -> int:
    entries = "".join(
        f'    ("{c}", include_str!("../defaults/{c}.json")),\n' for c in translated_codes()
    )
    src = STORAGE.read_text(encoding="utf-8")
    i, j = src.find(BEGIN), src.find(END)
    if i == -1 or j == -1 or j < i:
        print("storage.rs is missing the BEGIN/END GENERATED markers")
        return 1
    new = src[: i + len(BEGIN)] + entries + src[j:]
    if new == src:
        print("bundled language list is up to date")
        return 0
    if check:
        print("simplelang/src/storage.rs is out of date: run `python3 tools/translations.py sync`")
        return 1
    STORAGE.write_text(new, encoding="utf-8")
    print(f"updated the bundled language list in {STORAGE.relative_to(ROOT)}")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)

    s = sub.add_parser("status", help="show translation coverage")
    s.add_argument("--write", action="store_true", help="also (re)write TRANSLATIONS.md")
    s.set_defaults(fn=cmd_status)

    p = sub.add_parser("prompt", help="build LLM prompts")
    p.add_argument("codes", nargs="*", help="language codes, e.g. fr_fr es_mx")
    p.add_argument("--missing", action="store_true", help="every language without a translation")
    p.add_argument("--out", help="write one <code>.txt per language into this folder")
    p.set_defaults(fn=cmd_prompt)

    i = sub.add_parser("import", help="validate and add translations")
    i.add_argument("paths", nargs="+", help="reply files (named <code>.json) or folders of them")
    i.add_argument("--code", help="language code, if the file isn't named after it")
    i.add_argument("--overwrite", action="store_true", help="replace existing translations")
    i.set_defaults(fn=cmd_import)

    y = sub.add_parser("sync", help="update the Rust list of bundled languages")
    y.add_argument("--check", action="store_true", help="only check; exit 1 if out of date (for CI)")
    y.set_defaults(fn=lambda a: sync(a.check))

    args = ap.parse_args()
    return args.fn(args)


if __name__ == "__main__":
    sys.exit(main())
